name: flake-nightly

on:
  push:
    branches: [update_flake_lock_action]

jobs:
  flake:
    uses: ./.github/workflows/flake.yml
    secrets:
      ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

  push:
    needs: [flake]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Push to "nightly"
        run: |
          git checkout origin/update_flake_lock_action
          git checkout -B nightly
          git push --force --set-upstream origin nightly

